const profanities = {
    number: [
        { regex: /[4]{1,}[s]{1,}[k]{1,}[i]{1,}[n]{1,}/i, severe: false },
    ],
    text: [
        { regex: /[卐]{1,}/i, severe: true },
        { regex: /[f]{1,}(u|v|a|o|i|e|x){1,}[c]{0,}[k]{1,}/i, severe: false },
        { regex: /[f]{1,}(u|v|a|o|i|e|x){0,}[c]{1,}[k]{1,}/i, severe: false },
        { regex: /[f]{1,}(u|v|a|o|i|e|x){1,}[c]{2,}/i, severe: false },
        { regex: /[f]{1,}[c]{1,}(u|v|a|o|i|e|x){0,}[k]{1,}/i, severe: false },
        { regex: /[f]{1,}[k]{1,}(u|v|a|o|i|e|x){0,}[c]{1,}/i, severe: false },
        { regex: /[f]{1,}(u|v|a|o|i|e|x){1,}[c]{1,}[x]{1,}/i, severe: false },
        { regex: /[f]{1,}(u|v){1,}[g]{2,}/i, severe: false },
        { regex: /[f]{1,}(u|v){1,}[q]{1,}/i, severe: false },
        { regex: /[p]{1,}[h]{1,}(u|v|a|o|i|e|x){1,}[c]{0,}[k]{1,}/i, severe: false },
        { regex: /[p]{1,}[h]{1,}(u|v|a|o|i|e|x){1,}[c]{1,}/i, severe: false },
        { regex: /(?:^|\W)[s]{1,}[h]{1,}(i|a){0,}[t]{1,}/i, severe: false },
        { regex: /(n|h|j|w){1,}(i|y){0,}(g|c|k){2,}[e]{0,}[r]{1,}/i, severe: true },
        { regex: /(n|h|j|w){1,}(i|y){0,}(g|c|k){2,}[a]{1,}/i, severe: true },
        { regex: /[n]{1,}(i|y){0,}[g]{1,}[r]{1,}[e]{1,}/i, severe: true },
        { regex: /[n]{1,}(i|y){0,}[g]{1,}[u]{1,}[h]{1,}/i, severe: true },
        { regex: /[n]{1,}(i|y){1,}[g]{1,}[a]{1,}/i, severe: true },
        { regex: /[n]{1,}(i|y){1,}[g]{1,}( |-|_){0,}[n]{1,}(i|o){1,}[g]{1,}/i, severe: true },
        { regex: /(n|h|j|w){1,}(e|i|y){0,}[g]{1,}[r]{1,}[o]{1,}/i, severe: true },
        { regex: /[r]{1,}[e]{0,}[t]{1,}[a]{0,}[r]{1,}[d]{1,}/i, severe: true },
        { regex: /[d]{1,}[a]{1,}[m]{1,}[n]{1,}/i, severe: false },
        { regex: /[d]{1,}[a]{1,}[m]{2,}[i]{0,}[t]{1,}/i, severe: false },
        { regex: /(?:^|\W)[a]{1,}[s]{2,}/i, severe: false },
        { regex: /(?:^|\W)[a]{1,}[r]{1,}[s]{1,}[e]{1,}/i, severe: false },
        { regex: /[d]{1,}[u]{0,}[m]{1,}[b]{1,}( |-|_){0,}[a]{0,}[s]{2,}/i, severe: false },
        { regex: /[d]{1,}[u]{0,}[m]{1,}[b]{1,}( |-|_){0,}[a]{1,}[s]{1,}/i, severe: false },
        { regex: /(?:^|\W)[s]{1,}[e]{1,}[x]{1,}/i, severe: false },
        { regex: /(?:^|\W)[c]{1,}[u]{1,}[m]{1,}/i, severe: true },
        { regex: /[w]{1,}[h]{1,}[o]{0,}[r]{1,}[e]{1,}/i, severe: true },
        { regex: /[w]{1,}[h]{1,}[o]{1,}[a]{0,}[r]{1,}/i, severe: true },
        { regex: /[d]{1,}[i]{1,}[c]{0,}[k]{1,}/i, severe: false },
        { regex: /[d]{1,}[i]{1,}[c]{0,}[x]{1,}/i, severe: false },
        { regex: /(?:^|\W)[c]{1,}[o]{1,}[c]{1,}[k]{1,}/i, severe: false },
        { regex: /[c]{1,}[o]{1,}[k]{1,}/i, severe: false },
        { regex: /[c]{1,}[o]{1,}[c]{0,}[x]{1,}/i, severe: false },
        { regex: /[c]{1,}[a]{2,}[k]{1,}/i, severe: false },
        { regex: /[c]{1,}[a]{1,}[c]{1,}[k]{1,}/i, severe: false },
        { regex: /[c]{1,}[a]{1,}[w]{1,}[k]{1,}/i, severe: false },
        { regex: /[p]{1,}[e]{0,}[n]{1,}(i|y){1,}[s]{1,}/i, severe: false },
        { regex: /[o]{1,}[r]{1,}[g]{1,}[a]{1,}[s]{1,}[m]{1,}/i, severe: false },
        { regex: /[e]{1,}[j]{1,}[a]{1,}[c]{1,}[u]{1,}[l]{1,}[a]{1,}[t]{1,}[i]{1,}[o]{1,}[n]{1,}/i, severe: false },
        { regex: /[e]{1,}[j]{1,}[a]{1,}[k]{1,}[u]{1,}[l]{1,}[a]{1,}[t]{1,}[i]{1,}[o]{1,}[n]{1,}/i, severe: false },
        { regex: /[f]{1,}[o]{1,}[r]{1,}[e]{1,}[s]{1,}[k]{1,}[i]{1,}[n]{1,}/i, severe: false },
        { regex: /[f]{1,}[a]{1,}[g]{1,}/i, severe: true },
        { regex: /[f]{1,}[a]{0,}[g]{1,}[o]{1,}[t]{1,}/i, severe: true },
        { regex: /[f]{1,}[a]{0,}[g]{2,}[o]{0,}[t]{1,}/i, severe: true },
        { regex: /[s]{1,}[k]{1,}[a]{0,}[n]{1,}[k]{1,}/i, severe: false },
        { regex: /[a]{1,}[b]{1,}[e]{2,}[d]{1,}/i, severe: false },
        { regex: /[a]{1,}[n]{1,}[a]{1,}[l]{1,}/i, severe: false },
        { regex: /[b]{1,}[o]{2,}[b]{1,}/i, severe: false },
        { regex: /[b]{1,}[i]{1,}[a]{0,}[o]{0,}[t]{1,}[c]{1,}[h]{1,}/i, severe: false },
        { regex: /[b]{1,}[i]{1,}[o]{0,}[a]{0,}[t]{1,}[c]{1,}[h]{1,}/i, severe: false },
        { regex: /[b]{1,}[e]{2,}[o]{0,}[t]{1,}[c]{1,}[h]{1,}/i, severe: false },
        { regex: /[b]{1,}[e]{1,}[y]{1,}[o]{1,}[t]{0,}[c]{1,}[h]{1,}/i, severe: false },
        { regex: /[b]{1,}[i]{1,}[z]{2,}[a]{1,}[t]{0,}[c]{1,}[h]{1,}/i, severe: false },
        { regex: /[b]{1,}[o]{1,}[i]{1,}[o]{1,}[l]{1,}[a]{1,}/i, severe: false },
        { regex: /[b]{1,}[a]{1,}[n]{1,}[g]{1,}[b]{1,}[r]{1,}[o]{1,}/i, severe: false },
        { regex: /[b]{1,}[a]{1,}[l]{2,}[s]{1,}[a]{1,}[c]{1,}/i, severe: false },
        { regex: /[b]{1,}[a]{1,}[l]{2,}[s]{1,}[a]{1,}[c]{0,}[k]{1,}/i, severe: false },
        { regex: /[b]{1,}[a]{0,}[s]{1,}[t]{1,}[a]{0,}[r]{1,}[d]{1,}/i, severe: false },
        { regex: /[b]{1,}[a]{0,}[s]{1,}[t]{1,}[u]{0,}[r]{1,}[d]{1,}/i, severe: false },
        { regex: /[b]{1,}[a]{0,}[z]{1,}[t]{1,}[a]{0,}[r]{1,}[d]{1,}/i, severe: false },
        { regex: /[b]{1,}[a]{1,}[t]{1,}[e]{1,}[r]{1,}/i, severe: false },
        { regex: /[b]{1,}[a]{1,}[t]{1,}[e]{1,}[s]{1,}/i, severe: false },
        { regex: /[b]{1,}[e]{1,}[a]{1,}[n]{1,}[e]{1,}[r]{1,}/i, severe: false },
        { regex: /[b]{1,}[e]{1,}[l]{2,}[e]{1,}[n]{1,}[d]{1,}/i, severe: false },
        { regex: /[b]{1,}[e]{1,}[n]{1,}[d]{1,}[e]{1,}[r]{1,}/i, severe: false },
        { regex: /[b]{1,}[j]{1,}/i, severe: false },
        { regex: /[b]{1,}[l]{1,}[o]{1,}[w]{0,}[j]{1,}[o]{1,}[b]{1,}/i, severe: false },
        { regex: /[b]{1,}[l]{1,}[a]{1,}[c]{0,}[k]{1,}[y]{1,}/i, severe: true },
        { regex: /[b]{1,}[l]{1,}[u]{1,}[m]{1,}[p]{1,}[k]{1,}[i]{1,}[n]{1,}/i, severe: false },
        { regex: /[b]{1,}[o]{1,}[l]{2,}[o]{1,}[c]{0,}[k]{1,}/i, severe: false },
        { regex: /[b]{1,}[o]{1,}[l]{2,}[o]{1,}[x]{1,}/i, severe: false },
        { regex: /[b]{1,}[o]{1,}[n]{1,}[d]{1,}[a]{1,}[g]{1,}[e]{1,}/i, severe: false },
        { regex: /[b]{1,}[o]{1,}[n]{1,}[e]{0,}[r]{1,}/i, severe: false },
        { regex: /[b]{1,}[u]{1,}[n]{1,}[g]{1,}/i, severe: false },
        { regex: /[b]{1,}[u]{1,}[t]{1,}( |-|_){0,}[h]{1,}[o]{1,}[l]{1,}[e]{1,}/i, severe: false },
        { regex: /[c]{1,}[u]{1,}[n]{1,}[t]{1,}/i, severe: false },
        { regex: /[c]{1,}[o]{2,}[n]{1,}/i, severe: false },
        { regex: /[c]{1,}[o]{2,}[t]{1,}/i, severe: false },
        { regex: /[c]{1,}[o]{1,}[j]{1,}[o]{1,}[n]{1,}[e]{1,}/i, severe: false },
        { regex: /[c]{1,}[a]{1,}[m]{1,}[e]{1,}[l]{1,}( |-|_){0,}[t]{1,}[o]{1,}[e]{1,}/i, severe: false },
        { regex: /[c]{1,}[a]{1,}[m]{1,}[e]{1,}[l]{1,}( |-|_){0,}[j]{1,}[o]{1,}[c]{0,}[k]{1,}[e]{0,}[y]{1,}/i, severe: true },
        { regex: /[c]{1,}[a]{1,}[r]{1,}[p]{1,}[e]{1,}[t]{1,}( |-|_){0,}[m]{1,}[u]{0,}[n]{1,}[c]{1,}[h]{1,}/i, severe: true },
        { regex: /[c]{1,}[h]{1,}[i]{1,}[n]{1,}[k]{1,}/i, severe: true },
        { regex: /[c]{1,}[h]{1,}[i]{1,}[n]{1,}[a]{1,}( |-|_){0,}[v]{1,}[i]{1,}[r]{1,}[u]{1,}[s]{1,}/i, severe: true },
        { regex: /[c]{1,}[h]{1,}[i]{1,}[n]{1,}[e]{1,}[s]{1,}[e]{1,}( |-|_){0,}[v]{1,}[i]{1,}[r]{1,}[u]{1,}[s]{1,}/i, severe: false },
        { regex: /[c]{1,}[h]{1,}[i]{1,}[n]{1,}[g]{1,}( |-|_){0,}[c]{1,}[h]{1,}[o]{1,}[n]{1,}[g]{1,}/i, severe: false },
        { regex: /[c]{1,}[h]{1,}[o]{1,}[a]{1,}[d]{1,}/i, severe: false },
        { regex: /[c]{1,}[h]{1,}[o]{1,}[c]{1,}[h]{1,}[a]{1,}/i, severe: false },
        { regex: /[c]{1,}[h]{1,}[o]{1,}[l]{1,}[o]{1,}/i, severe: false },
        { regex: /(c|k){1,}[l]{1,}[i]{1,}[t]{1,}/i, severe: false },
        { regex: /[c]{1,}[o]{2,}[l]{1,}[i]{1,}[e]{1,}/i, severe: false },
        { regex: /[c]{1,}[o]{0,}[t]{2,}[o]{0,}[n]{1,}( |-|_){0,}[p]{1,}[i]{0,}[c]{0,}[k]{1,}[e]{0,}[r]{1,}/i, severe: true },
        { regex: /[m]{1,}[o]{1,}[f]{1,}[o]{1,}/i, severe: false },
        { regex: /[c]{1,}[r]{1,}[e]{1,}[a]{1,}[m]{1,}( |-|_){0,}[p]{1,}[i]{1,}[e]{1,}/i, severe: false },
        { regex: /[c]{1,}[u]{1,}[n]{1,}[i]{1,}[l]{1,}[i]{1,}[n]{1,}[g]{1,}[u]{1,}[s]{1,}/i, severe: false },
        { regex: /[d]{1,}[i]{1,}[l]{1,}[d]{1,}[o]{1,}/i, severe: false },
        { regex: /[d]{1,}[o]{1,}[g]{1,}[y]{0,}( |-|_){0,}[s]{1,}[t]{1,}[y]{1,}[l]{1,}[e]{1,}/i, severe: false },
        { regex: /[d]{1,}[o]{1,}[g]{1,}[i]{1,}[e]{1,}( |-|_){0,}[s]{1,}[t]{1,}[y]{1,}[l]{1,}[e]{1,}/i, severe: false },
        { regex: /[d]{1,}[a]{1,}[g]{1,}[o]{1,}/i, severe: false },
        { regex: /[d]{1,}[a]{1,}[r]{1,}[k]{1,}[t]{1,}[a]{1,}[r]{1,}[d]{1,}/i, severe: true },
        { regex: /[d]{1,}[i]{0,}[d]{2,}[l]{1,}[e]{1,}/i, severe: false },
        { regex: /[d]{1,}[i]{0,}[r]{1,}[t]{1,}[y]{1,}( |-|_){0,}[s]{1,}[a]{0,}[n]{1,}[c]{1,}[h]{1,}[e]{0,}[z]{1,}/i, severe: false },
        { regex: /[d]{1,}[o]{1,}[l]{1,}[t]{1,}/i, severe: false },
        { regex: /[d]{1,}[y]{1,}[k]{1,}[e]{1,}/i, severe: false },
        { regex: /[e]{1,}[r]{1,}[e]{1,}[c]{1,}[t]{1,}[o]{1,}[p]{1,}[l]{1,}[a]{1,}[s]{1,}[m]{1,}/i, severe: false },
        { regex: /[f]{1,}[e]{1,}[l]{1,}[a]{1,}[t]{1,}[i]{1,}[o]{1,}/i, severe: false },
        { regex: /[f]{1,}[i]{0,}[n]{1,}[g]{1,}[e]{0,}[r]{1,}( |-|_){0,}[b]{1,}[a]{0,}[n]{1,}[g]{1,}/i, severe: false },
        { regex: /[f]{1,}[i]{0,}[n]{1,}[g]{1,}[e]{0,}[r]{1,}( |-|_){0,}[p]{1,}[o]{1,}[p]{1,}/i, severe: false },
        { regex: /[f]{1,}[l]{1,}[a]{1,}[m]{1,}[e]{0,}[r]{1,}/i, severe: false },
        { regex: /[f]{1,}[e]{0,}[m]{1,}[e]{0,}( |-|_){0,}[b]{1,}[o]{1,}(i|y){1,}/i, severe: true },
        { regex: /[f]{1,}[o]{0,}[t]{1,}[h]{1,}[e]{0,}[r]{1,}( |-|_){0,}[m]{1,}(u|v|a|o|i|e|x){0,}[c]{0,}[k]{1,}[e]{0,}[r]{1,}/i, severe: false },
        { regex: /[f]{1,}[o]{0,}[d]{1,}[e]{0,}[r]{1,}( |-|_){0,}[m]{1,}(u|v|a|o|i|e|x){0,}[c]{0,}[k]{1,}[e]{0,}[r]{1,}/i, severe: false },
        { regex: /[f]{1,}[a]{1,}[p]{1,}/i, severe: true },
        { regex: /[f]{1,}[u]{0,}[d]{1,}[g]{1,}[e]{1,}( |-|_){0,}[p]{1,}[a]{0,}[c]{0,}[k]{1,}[e]{0,}[r]{1,}/i, severe: true },
        { regex: /[g]{1,}[a]{1,}[y]{1,}( |-|_){0,}[l]{1,}[o]{1,}[r]{1,}[d]{1,}/i, severe: true },
        { regex: /[g]{1,}[a]{1,}[y]{1,}( |-|_){0,}[w]{1,}[a]{1,}[d]{1,}/i, severe: true },
        { regex: /[g]{1,}[o]{2,}[k]{1,}/i, severe: false },
        { regex: /[g]{1,}[o]{1,}[w]{1,}[l]{1,}/i, severe: false },
        { regex: /[g]{1,}[r]{1,}[o]{1,}[i]{1,}[d]{1,}/i, severe: false },
        { regex: /[h]{1,}[e]{0,}[b]{1,}[e]{1,}/i, severe: false },
        { regex: /[h]{1,}[o]{1,}[a]{1,}[r]{1,}/i, severe: false },
        { regex: /[h]{1,}[o]{2,}[r]{1,}/i, severe: true },
        { regex: /[h]{1,}[e]{1,}[i]{1,}[l]{1,}/i, severe: true },
        { regex: /[i]{1,}[n]{1,}[j]{1,}[u]{0,}[n]{1,}/i, severe: true },
        { regex: /[j]{1,}(a|c){0,}[k]{1,}( |-|_){0,}[o]{1,}[f]{2,}/i, severe: false },
        { regex: /[j]{1,}[a]{0,}[c]{1,}[k]{0,}( |-|_){0,}[o]{1,}[f]{2,}/i, severe: false },
        { regex: /[j]{1,}[e]{0,}[r]{1,}[k]{1,}( |-|_){0,}[o]{1,}[f]{2,}/i, severe: false },
        { regex: /[j]{1,}[a]{0,}[g]{1,}( |-|_){0,}[o]{1,}[f]{2,}/i, severe: false },
        { regex: /[j]{1,}[a]{1,}[p]{1,}/i, severe: true },
        { regex: /[j]{1,}[i]{1,}[g]{2,}/i, severe: false },
        { regex: /[j]{1,}[i]{0,}[z]{2,}/i, severe: false },
        { regex: /[k]{1,}(i|y){1,}[k]{1,}[e]{1,}/i, severe: false },
        { regex: /(?:^|\W)kkk(?:$|\W)/i, severe: true },
        { regex: /[k]{1,}[l]{1,}[a]{1,}[n]{1,}/i, severe: true },
        { regex: /[k]{1,}[l]{1,}[u]{0,}[x]{1,}[e]{0,}[r]{1,}/i, severe: true },
        { regex: /[k]{1,}[i]{0,}[t]{1,}[y]( |-|_){0,}[p]{1,}[u]{0,}[n]{1,}[c]{0,}[h]{1,}[e]{0,}[r]{1,}/i, severe: false },
        { regex: /(?:^|\W)[k]{1,}[y]{1,}[s]{1,}/i, severe: true },
        { regex: /[k]{1,}[i]{1,}[l]{1,}( |-|_){0,}[y]{0,}[o]{0,}[u]{1,}[r]{1,}( |-|_){0,}[s]{1,}[e]{0,}[l]{1,}[f]{1,}/i, severe: true },
        { regex: /[k]{1,}[i]{0,}[l]{2,}( |-|_){0,}[y]{0,}[o]{0,}[u]{1,}[r]{1,}( |-|_){0,}[s]{1,}[e]{0,}[l]{1,}[f]{1,}/i, severe: true },
        { regex: /[k]{1,}[i]{1,}[l]{1,}( |-|_){0,}[y]{1,}[o]{0,}[u]{0,}[r]{0,}( |-|_){0,}[s]{1,}[e]{0,}[l]{1,}[f]{1,}/i, severe: true },
        { regex: /[k]{1,}[i]{0,}[l]{2,}( |-|_){0,}[y]{0,}[o]{0,}[u]{1,}[r]{1,}( |-|_){0,}[s]{1,}[e]{0,}[l]{1,}[f]{1,}/i, severe: true },
        { regex: /[k]{1,}[i]{1,}[l]{1,}( |-|_){0,}[t]{1,}[h]{1,}[y]{0,}( |-|_){0,}[s]{1,}[e]{0,}[l]{1,}[f]{1,}/i, severe: true },
        { regex: /[k]{1,}[i]{0,}[l]{2,}( |-|_){0,}[t]{1,}[h]{1,}[y]{0,}( |-|_){0,}[s]{1,}[e]{0,}[l]{1,}[f]{1,}/i, severe: true },
        { regex: /[l]{1,}[a]{0,}[d]{1,}(i|y){1,}[b]{1,}[o]{1,}(i|y){1,}/i, severe: true },
        { regex: /[l]{1,}[e]{0,}[s]{1,}[b]{1,}[o]{1,}/i, severe: false },
        { regex: /[l]{1,}[i]{0,}[g]{1,}[m]{1,}[a]{1,}/i, severe: false },
        { regex: /[m]{1,}[a]{0,}[s]{1,}[t]{1,}(u|e){0,}[r]{1,}( |-|_){0,}[b]{1,}[a]{0,}[t]{1,}/i, severe: false },
        { regex: /[m]{1,}[f]{1,}('|"|’){0,}[e]{1,}[r]{1,}/i, severe: false },
        { regex: /[m]{1,}[f]{1,}('|"|’){0,}[i]{0,}[n]{1,}[g]{1,}/i, severe: false },
        { regex: /[m]{1,}[f]{1,}[k]{1,}[e]{0,}[r]{1,}/i, severe: false },
        { regex: /[m]{1,}[i]{0,}[l]{1,}[f]{1,}/i, severe: false },
        { regex: /[m]{1,}[o]{1,}[l]{1,}[e]{0,}[s]{1,}[t]{1,}/i, severe: false },
        { regex: /[m]{1,}[o]{1,}[n]{1,}[g]{1,}/i, severe: false },
        { regex: /[s]{1,}[h]{1,}[r]{1,}[o]{0,}[m]{1,}( |-|_){0,}[t]{1,}[i]{1,}[p]{1,}/i, severe: false },
        { regex: /[n]{1,}[o]{1,}[b]{1,}( |-|_){0,}[j]{1,}[o]{1,}[c]{0,}[k]{1,}[e]{0,}[y]{1,}/i, severe: true },
        { regex: /[n]{1,}[o]{0,}[n]{1,}[c]{1,}[e]{1,}/i, severe: true },
        { regex: /[n]{1,}[u]{0,}[t]{1,}[s]{1,}[a]{0,}[c]{0,}[k]{1,}/i, severe: false },
        { regex: /[n]{1,}[u]{0,}[t]{1,}[s]{1,}[a]{0,}[c]{1,}/i, severe: false },
        { regex: /[n]{1,}[y]{1,}[m]{1,}[p]{1,}[h]{1,}[o]{1,}/i, severe: false },
        { regex: /[o]{1,}[v]{1,}[e]{0,}[n]{1,}( |-|_){0,}[d]{1,}[o]{1,}[d]{0,}[g]{1,}[e]{0,}[r]{1,}/i, severe: true },
        { regex: /(p|h){1,}[u]{0,}(s|z){2,}(i|y){1,}/i, severe: false },
        { regex: /(?:^|\W)[p]{1,}[a]{1,}[k]{1,}[i]{1,}(s|z){0,}(?:$|\W)/i, severe: true },
        { regex: /(?:^|\W)[p]{1,}[e]{1,}[d]{1,}[o]{1,}/i, severe: true },
        { regex: /(?:^|\W)[p]{1,}[e]{2,}[n]{1,}/i, severe: false },
        { regex: /[p]{1,}[e]{0,}[t]{1,}[e]{0,}[r]{1,}( |-|_){0,}[p]{1,}[u]{0,}[f]{1,}[e]{0,}[r]{1,}/i, severe: false },
        { regex: /[p]{1,}[h]{1,}[a]{0,}[g]{1,}[o]{1,}[t]{1,}/i, severe: true },
        { regex: /[p]{1,}[i]{0,}[l]{2,}[o]{0,}[w]{1,}( |-|_){0,}[b]{1,}[i]{1,}[t]{1,}[e]{0,}[r]{1,}/i, severe: false },
        { regex: /[p]{1,}[i]{0,}[s]{2,}( |-|_){0,}[o]{1,}[f]{2,}/i, severe: false },
        { regex: /[p]{1,}[o]{1,}[l]{1,}[e]{1,}( |-|_){0,}[l]{1,}[i]{0,}[c]{0,}[k]{1,}[e]{0,}[r]{1,}/i, severe: false },
        { regex: /[p]{1,}[o]{1,}[l]{1,}[e]{1,}( |-|_){0,}[l]{1,}[i]{0,}[c]{1,}[k]{0,}[e]{0,}[r]{1,}/i, severe: false },
        { regex: /[p]{1,}[o]{1,}[l]{1,}[e]{1,}( |-|_){0,}[s]{1,}[u]{0,}[c]{0,}[k]{1,}[e]{0,}[r]{1,}/i, severe: false },
        { regex: /[p]{1,}[o]{1,}[l]{1,}[e]{1,}( |-|_){0,}[s]{1,}[u]{0,}[c]{1,}[k]{0,}[e]{0,}[r]{1,}/i, severe: false },
        { regex: /[p]{1,}[o]{1,}[l]{1,}[e]{1,}( |-|_){0,}[s]{1,}[m]{1,}[o]{0,}[k]{1,}[e]{0,}[r]{1,}/i, severe: false },
        { regex: /[p]{1,}[u]{0,}[n]{1,}[a]{1,}[n]{1,}[i]{1,}/i, severe: false },
        { regex: /[p]{1,}[u]{0,}[n]{1,}[t]{1,}[a]{1,}/i, severe: false },
        { regex: /[p]{1,}[o]{0,}[r]{1,}[c]{1,}[h]{1,}( |-|_){0,}[m]{1,}[o]{0,}[n]{1,}[k]{1,}[e]{0,}[y]{1,}/i, severe: false },
        { regex: /[p]{1,}[o]{0,}[r]{1,}[c]{1,}[h]{1,}( |-|_){0,}[m]{1,}[o]{0,}[n]{1,}[k]{1,}[e]{1,}/i, severe: false },
        { regex: /[q]{1,}[u]{1,}[e]{1,}[r]{1,}(?:^|\W)/i, severe: true },
        { regex: /[r]{1,}[a]{0,}[p]{1,}[e]{1,}/i, severe: true },
        { regex: /[r]{1,}[a]{0,}[p]{1,}[i]{0,}[s]{1,}[t]{1,}/i, severe: true },
        { regex: /[r]{1,}[a]{0,}[g]{1,}( |-|_){0,}[h]{1,}[e]{0,}[a]{0,}[d]{1,}/i, severe: false },
        { regex: /[r]{1,}[a]{0,}[g]{1,}( |-|_){0,}[t]{1,}[a]{0,}[r]{1,}[d]{1,}/i, severe: true },
        { regex: /[r]{1,}[e]{1,}[d]{1,}( |-|_){0,}[s]{1,}[k]{1,}[i]{0,}[n]{1,}/i, severe: false },
        { regex: /[r]{1,}[e]{1,}[d]{1,}( |-|_){0,}[n]{1,}[e]{0,}[c]{0,}[k]{1,}/i, severe: false },
        { regex: /[r]{1,}[i]{1,}[c]{1,}[e]{1,}( |-|_){0,}[m]{1,}[o]{0,}[n]{1,}[k]{1,}[e]{0,}[y]{1,}/i, severe: false },
        { regex: /[r]{1,}[i]{1,}[c]{1,}[e]{1,}( |-|_){0,}[m]{1,}[o]{0,}[n]{1,}[k]{1,}[e]{1,}/i, severe: false },
        { regex: /[r]{1,}[i]{1,}[m]{1,}( |-|_){0,}[j]{1,}[o]{1,}[b]{1,}/i, severe: true },
        { regex: /[s]{1,}[l]{1,}[u]{0,}[t]{1,}/i, severe: true },
        { regex: /(?:^|\W)[s]{1,}(?:$|\W)( |-|_){0,}[a]{1,}[n]{1,}[d]{1,}( |-|_){0,}(?:^|\W)[m]{1,}(?:$|\W)/i, severe: true },
        { regex: /(?:^|\W)[s]{1,}(?:$|\W)( |-|_){0,}('|"|’){0,}[n]{1,}('|"|’){0,}( |-|_){0,}(?:^|\W)[m]{1,}(?:$|\W)/i, severe: true },
        { regex: /[s]{1,}[a]{1,}[l]{1,}[a]{1,}[d]{1,}( |-|_){0,}[t]{1,}[o]{0,}[s]{1,}[e]{0,}[r]{1,}/i, severe: false },
        { regex: /[s]{1,}[a]{0,}[m]{1,}[b]{1,}[o]{1,}/i, severe: false },
        { regex: /[s]{1,}[c]{1,}[u]{1,}[m]{1,}/i, severe: false },
        { regex: /[s]{1,}[h]{1,}[e]{0,}( |-|_){0,}[m]{1,}[a]{1,}[l]{1,}[e]{1,}/i, severe: true },
        { regex: /[s]{1,}[c]{1,}[h]{1,}[e]{1,}[i]{1,}[s]{1,}[t]{1,}[e]{0,}[r]{1,}/i, severe: false },
        { regex: /[s]{1,}[h]{1,}[i]{0,}[d]{1,}[i]{0,}[c]{0,}[k]{1,}/i, severe: false },
        { regex: /[s]{1,}[h]{1,}[i]{0,}[d]{1,}[i]{0,}[c]{1,}/i, severe: false },
        { regex: /[s]{1,}[h]{1,}[i]{0,}[p]{1,}[d]{1,}[i]{0,}[t]{1,}/i, severe: false },
        { regex: /[s]{1,}[h]{1,}[y]{1,}[l]{1,}[o]{1,}[c]{1,}[k]{1,}/i, severe: false },
        { regex: /[s]{1,}[l]{1,}[a]{0,}[n]{1,}[t]{1,}( |-|_){0,}[e]{1,}[y]{1,}[e]{1,}/i, severe: true },
        { regex: /[s]{1,}[l]{1,}[a]{1,}[g]{1,}/i, severe: false },
        { regex: /[s]{1,}[p]{1,}[i]{1,}(c|k|x|g){1,}/i, severe: false },
        { regex: /[s]{1,}[t]{1,}[f]{1,}[u]{1,}/i, severe: false },
        { regex: /[s]{1,}[t]{1,}[u]{0,}[p]{1,}[i]{0,}[d]{1,}( |-|_){0,}[a]{0,}[s]{2,}/i, severe: false },
        { regex: /[s]{1,}[t]{1,}[u]{0,}[p]{1,}[i]{0,}[d]{1,}( |-|_){0,}[a]{1,}[s]{1,}/i, severe: false },
        { regex: /[s]{1,}[u]{0,}[c]{0,}[k]{1,}( |-|_){0,}[o]{1,}[f]{2,}/i, severe: false },
        { regex: /[s]{1,}[u]{0,}[g]{1,}( |-|_){0,}[o]{1,}[f]{2,}/i, severe: false },
        { regex: /[s]{1,}[u]{1,}[g]{1,}[m]{1,}[a]{1,}/i, severe: false },
        { regex: /[t]{1,}[a]{1,}[c]{1,}[o]{1,}( |-|_){0,}[h]{1,}[e]{1,}[a]{1,}[d]{1,}/i, severe: true },
        { regex: /[t]{1,}[a]{1,}[d]{1,}[g]{1,}[e]{0,}[r]{1,}/i, severe: false },
        { regex: /[t]{1,}[a]{1,}[r]{1,}( |-|_){0,}[b]{1,}[a]{0,}[b]{1,}(i|y){1,}/i, severe: true },
        { regex: /[t]{1,}[h]{1,}[r]{1,}[o]{1,}[a]{0,}[t]{1,}[e]{0,}[r]{1,}/i, severe: false },
        { regex: /[t]{1,}[i]{1,}[t]{1,}(s|z){1,}/i, severe: false },
        { regex: /[t]{1,}[i]{1,}[t]{2,}(i|y){1,}/i, severe: false },
        { regex: /[t]{1,}[o]{0,}[w]{1,}[e]{0,}[l]{1,}( |-|_){0,}[h]{1,}[e]{1,}[a]{1,}[d]{1,}/i, severe: true },
        { regex: /[t]{1,}[r]{1,}[a]{0,}[m]{1,}[p]{1,}/i, severe: false },
        { regex: /[t]{1,}[r]{1,}[a]{0,}[n]{1,}(i|y){1,}/i, severe: true },
        { regex: /[t]{1,}[r]{1,}[a]{0,}[n]{1,}(s|z){1,}( |-|_){0,}[v]{1,}[e]{0,}[s]{1,}[t]{1,}[i]{0,}[t]{1,}[e]{0,}/i, severe: false },
        { regex: /[t]{1,}[w]{1,}[a]{1,}[t]{1,}/i, severe: false },
        { regex: /(?:^|\W)[t]{1,}[w]{1,}[i]{1,}[n]{1,}[k]{1,}(s|z){0,}(?:$|\W)/i, severe: false },
        { regex: /[v]{1,}[a]{1,}(g|j){1,}/i, severe: false },
        { regex: /[v]{1,}[a]{0,}[g]{1,}[i]{0,}[n]{1,}[a]{1,}/i, severe: false },
        { regex: /[v]{1,}[u]{0,}[l]{1,}[v]{1,}[a]{1,}/i, severe: false },
        { regex: /[w]{1,}[a]{0,}[n]{1,}[k]{1,}/i, severe: false },
        { regex: /[w]{1,}[e]{1,}[t]{1,}( |-|_){0,}[b]{1,}[a]{0,}[c]{0,}[k]{1,}/i, severe: false },
        { regex: /[w]{1,}[e]{1,}[t]{1,}( |-|_){0,}[b]{1,}[a]{0,}[c]{1,}/i, severe: false },
        { regex: /[w]{1,}[h]{0,}[a]{1,}[c]{0,}[k]{1,}( |-|_){0,}[o]{1,}[f]{2,}/i, severe: false },
        { regex: /[w]{1,}[i]{0,}[n]{1,}[d]{1,}[o]{0,}[w]{1,}( |-|_){0,}[l]{1,}[i]{0,}[c]{0,}[k]{1,}[e]{0,}[r]{1,}/i, severe: true },
        { regex: /(?:^|\W)[w]{1,}[o]{1,}[p]{1,}(?:^|\W)/i, severe: false },
        { regex: /[z]{1,}[i]{0,}[p]{1,}[e]{0,}[r]{1,}( |-|_){0,}[h]{1,}[e]{1,}[a]{1,}[d]{1,}/i, severe: true },
    ],
};


exports.isProfane = function (input) {
    var i, str1, str2;

    str1 = input.replace(/[^0-9a-z+@!#$'"’\-_]/gi, " ").replace(/[ ]{2,}/g, " ").toLowerCase();
    for (i = 0; i < profanities.number.length; i++) {
        if (profanities.number[i].regex.test(str1)) {
            return true;
        }
    }

    str2 = str1.replace(/(4|@)/g, "a").replace(/8/g, "b").replace(/3/g, "e").replace(/#/g, "h").replace(/(1|!)/g, "i").replace(/0/g, "o").replace(/(5|\$)/g, "s").replace(/\+/g, "t").replace(/(λ|¥)/g, "y").replace(/2/g, "z").toLowerCase();
    for (i = 0; i < profanities.text.length; i++) {
        if (profanities.text[i].regex.test(str2)) {
            return true;
        }
    }

    return false;
}